global:
  version: "1.0"
  active: default
  debug: false
  fogportalprofile:
    fogpip: ""
    fogpport: ""
    fogpapiprefix: ""
    fogpurlscheme: ""
  dockerconfig:
    server_uri: ""
    api_version: ""
author:
  name: |2+

  link: ""
profiles: {default: {host_ip: 172.19.88.11, host_port: 8443, auth_keys: ZGV2ZWxvcGVyOkNpc2NvMTIzIQ==,
    auth_token: fcdfa837-4ef6-4917-85df-3df923fcd5a4, local_repo: /software/downloads,
    api_prefix: /iox/api/v2/hosting/, url_scheme: https, ssh_port: 2222, rsa_key: "",
    certificate: "", cpu_architecture: "", middleware: {mw_ip: "", mw_port: "", mw_baseuri: "",
      mw_urlscheme: "", mw_access_token: ""}, conn_timeout: 1000}}